import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = resolve(rootDir, '.env');
const outputPath = resolve(rootDir, 'src/environments/environment.ts');

const defaults = {
  TASKFLOW_API_BASE_URL: 'http://localhost:3000',
  TASKFLOW_STORAGE_PREFIX: 'taskflow',
  TASKFLOW_SEARCH_DEBOUNCE_MS: '300',
  TASKFLOW_AUTOSAVE_DEBOUNCE_MS: '600',
  TASKFLOW_SCROLL_THROTTLE_MS: '250',
  TASKFLOW_POLLING_INTERVAL_MS: '10000',
  TASKFLOW_SNACKBAR_DURATION_MS: '2200',
  TASKFLOW_ERROR_SNACKBAR_DURATION_MS: '3000',
};

const envValues = {
  ...defaults,
  ...readEnvFile(envPath),
  ...pickProcessEnv(defaults),
};

const environment = {
  apiBaseUrl: requireText(envValues, 'TASKFLOW_API_BASE_URL'),
  storagePrefix: requireText(envValues, 'TASKFLOW_STORAGE_PREFIX'),
  timings: {
    searchDebounceMs: requireNumber(envValues, 'TASKFLOW_SEARCH_DEBOUNCE_MS'),
    autosaveDebounceMs: requireNumber(envValues, 'TASKFLOW_AUTOSAVE_DEBOUNCE_MS'),
    scrollThrottleMs: requireNumber(envValues, 'TASKFLOW_SCROLL_THROTTLE_MS'),
    pollingIntervalMs: requireNumber(envValues, 'TASKFLOW_POLLING_INTERVAL_MS'),
    snackbarDurationMs: requireNumber(envValues, 'TASKFLOW_SNACKBAR_DURATION_MS'),
    errorSnackbarDurationMs: requireNumber(envValues, 'TASKFLOW_ERROR_SNACKBAR_DURATION_MS'),
  },
};

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `// This file is generated by scripts/generate-env.mjs. Do not edit it manually.\n` +
    `// Update .env or .env.example, then rerun npm start/build/test.\n\n` +
    `export const environment = ${JSON.stringify(environment, null, 2)} as const;\n`,
);

console.log(`Generated ${outputPath}`);

function readEnvFile(path) {
  if (!existsSync(path)) {
    return {};
  }

  return readFileSync(path, 'utf8')
    .split(/\r?\n/)
    .reduce((values, line) => {
      const trimmedLine = line.trim();
      if (!trimmedLine || trimmedLine.startsWith('#')) {
        return values;
      }

      const separatorIndex = trimmedLine.indexOf('=');
      if (separatorIndex === -1) {
        return values;
      }

      const key = trimmedLine.slice(0, separatorIndex).trim();
      const value = trimmedLine.slice(separatorIndex + 1).trim().replace(/^['"]|['"]$/g, '');

      return { ...values, [key]: value };
    }, {});
}

function pickProcessEnv(keys) {
  return Object.keys(keys).reduce((values, key) => {
    if (process.env[key] === undefined) {
      return values;
    }

    return { ...values, [key]: process.env[key] };
  }, {});
}

function requireText(values, key) {
  const value = values[key]?.trim();
  if (!value) {
    throw new Error(`${key} is required.`);
  }

  return value;
}

function requireNumber(values, key) {
  const value = Number(values[key]);
  if (!Number.isFinite(value) || value < 0) {
    throw new Error(`${key} must be a non-negative number.`);
  }

  return value;
}
