// This file is generated by scripts/generate-env.mjs. Do not edit it manually.
// Update .env or .env.example, then rerun npm start/build/test.

export const environment = {
  "apiBaseUrl": "http://localhost:3000",
  "storagePrefix": "taskflow",
  "timings": {
    "searchDebounceMs": 300,
    "autosaveDebounceMs": 600,
    "scrollThrottleMs": 250,
    "pollingIntervalMs": 10000,
    "snackbarDurationMs": 2200,
    "errorSnackbarDurationMs": 3000
  }
} as const;
