### dang nhap
POST http://localhost:8017/v1/users/login
Content-Type: application/json

{
    "email": "trungquandev.official@gmail.com",
    "password": "trungquandev@123"
}

### gen new access token
PUT http://localhost:8017/v1/users/refresh_token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRydW5ncXVhbmRldi1zYW1wbGUtaWQtMTIzNDU2NzgiLCJlbWFpbCI6InRydW5ncXVhbmRldi5vZmZpY2lhbEBnbWFpbC5jb20iLCJpYXQiOjE3MjIyNTEyNjMsImV4cCI6MTcyMjI1NDg2M30.0mgqh1f7MRvquWt9UEUZGARbtEai_D1vxgWGgLz8xeg"
  }