version: '3.8'
services:
  dev-database:
    image: postgres:16.4
    container_name: dev-database
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestAuthDB
    networks:
      - nestjs-networks
networks:
  nestjs-networks:
